function DUM = CST2DUM(rootname,Nports,R0,CSTversion,isreciprocal,pindex,RootFigHandle);
%
%	DUM = CST2DUM(rootname,Nports,R0,CSTversion,isreciprocal,pindex)
%
% This function loads time-domain data from the output files
% generated by CST and creates a standard multiport
% data structure DUM. The rootname is used to build
% the names of expected data files according to the
% naming convention of CST software. The number of
% ports must be explicitely given by the user, as well
% as the (unique) reference resistance R0 used for the
% definition of the transient waves.
%
% No checks are performed on the format of input data files.
% However, the user has the flexibility of reading both
% version 3 data files (without header) or version 4 data
% files (with header, which is skipped. The argument
% CSTversion selects the format of data files to be read.
% If this argument is missing version 5 is adopted.
% This leads to an error in the read statements if version 4
% data files are processed, so this default choice is safe.
%
% Note that the time axis referring to different port
% excitations may be different. A time resampling is
% performed in order to have same sampling time and
% for all responses. The resulting DUM has
% a uniform time sampling but possibly different time
% axis lengths.
%
% The argument isreciprocal is a flag specifying
% whether the data to be read correspond to a reciprocal
% structure. If 1, the data are post-processed in order
% to store in DUM only the "best" responses. For each
% off-diagonal entry, the one with a longer time responses
% is retained, and the other is left empty.
%
% The optional argument pindex is a Nports x Nports
% matrix of '0' or '1' elements. This should be used if
% some specific port responses are to
% be flagged as 'non valid' a priori, without even
% checking for existing data. Valid ports are flagged
% with '1' in the corresponding element, while non valid
% ports are flagged with '0'. The default is ones(Nports). 
%
% ------------------------------
% Author: Stefano Grivet-Talocia
% Date: February 4, 2003
% Last revision: March 17, 2005
% ------------------------------
