function DUM = FDTD2DUM(pathname,rootname,Nports,R0,isreciprocal,pindex,RootFigHandle);
%
%	DUM = FDTD2DUM(pathname,rootname,Nports,R0,isreciprocal,pindex);
%
% This function loads time-domain data from the output files
% generated by FDTD and creates a standard multiport
% data structure DUM. The rootname is used to build
% the names of expected data files according to the
% naming convention of FDTD software, i.e. data files
% will be 
%
%   <pathname>/<rootname>_INXX/<rootname>_INXX_PORTS.OUT
%
% where XX is the two-digit excited port number.
% Note that <pathname> must be complete.
%
% No checks are performed on the format of input data files.
% The format must be in compliance with FDTD output files.
%
% Note that the time axis referring to different port
% excitations may be different. A time resampling is
% performed in order to have same sampling time and
% for all parameters. The resulting DUM has
% a unique sampling time and possibly different time duration.
%
% The argument isreciprocal is a flag specifying
% whether the data to be read correspond to a reciprocal
% structure. If 1, the data are post-processed in order
% to store in DUM only the "best" responses. For each
% off-diagonal entry, the one with a longer time responses
% is retained, and the other is left empty.
%
% The optional argument pindex is a Nports x Nports
% matrix of '0' or '1' elements. This should be used if
% some specific port responses are to
% be flagged as 'non valid' a priori, without even
% checking for existing data. Valid ports are flagged
% with '1' in the corresponding element, while non valid
% ports are flagged with '0'. The default is ones(Nports). 
%
% ------------------------------
% Author: Stefano Grivet-Talocia
% Date: January 30, 2003
% Last revision: November 12, 2003
% ------------------------------
