function MOD = Split2MOD(Omega,Nports,R0,RootFigHandle);
%
%	MOD = Split2MOD(Omega,Nports,R0)
%
% This function converts the separate sets of poles/residues
% stored in Omega into a standard MOD format (both poles/residues
% and state-space representations). The set Omega is generated
% via separate identification of subsets of port responses.
% It is a cell array with a number of cells equal to the number
% of different subsets. Each cell {k} of Omega is a structure
% with the following fields: 
%
% Omega{k}.pindex  (selector matrix of port responses in cell k)
% Omega{k}.p4poles (selector matrix of responses used for computing poles)
% Omega{k}.rp      (array of real poles for cell k)
% Omega{k}.cp      (array of complex poles for cell k)
% Omega{k}.rr      (cell matrix of real residues for cell k)
% Omega{k}.cr      (cell matrix of complexresidues for cell k)
% Omega{k}.dc      (cell matrix of direct coupling constants for cell k)
% Omeha{k}.err     (maximum approximation error for cell k)
%
% The structure Omega is generated by SplitPorts (the field pindex) and
% by any ****_Split function performing the partial rational approximation
% of the selected port responses. The function Split2MOD is intended as
% an "internal" utility function for format conversion.
% The other input arguments Nports and R0 are the number of ports and the
% reference resistance for the multiport being modeled. Note that the
% MOD being generated is in sparse format.
%
% ------------------------------
% Author: Stefano Grivet-Talocia
%         Andrea Ubolli
% Date: April 22, 2003
% Last modified: February 11, 2005
% ------------------------------
